sudo: false

addons:
  apt:
    packages:
      - git
      - nasm
      - realpath
      - makeinfo
      - libmpc-dev
      - libgmp-dev
      - libmpfr-dev
      - texinfo


branches:
  only:
    - ptrace

script: ./configure && make toolchain apps64 kernel
