#!/bin/sh

printf "Initializing network... "

if ! modprobe rtl8139 &>/dev/null; then
  echo "failed";
else
  ifc -i nd1 -n 10.0.0.2/8 -s up -b 10.255.255.255
  route -a -i nd1 -n 10.0.0.0/8 
  modprobe lo
  ifc -i nd2 -n 127.0.0.1/8 -s up -b 127.255.255.255
  route -a -i nd2 -n 127.0.0.0/8
  echo "ok";
fi

if [ ! -e /etc/firstbootdate ]; then
	sh /sys/first_run.sh
fi

login </dev/tty1 >/dev/tty1 2>/dev/tty1 &
login </dev/tty2 >/dev/tty2 2>/dev/tty2 &

login </dev/tty3 >/dev/tty3 2>/dev/tty3 &
. /etc/rc/rand start
. /etc/rc/loop start
