#!/bin/sh

echo "Initializing network... "

modprobe ethernet
modprobe rtl8139
modprobe ipv4
modprobe udp

(

ifc -i nd1 -n 10.0.0.2/8 -s up -b 10.255.255.255
route -a -i nd1 -n 10.0.0.0/8 

NUM=$(ls /dev/nd* 2>/dev/null | wc -l)
LOOP=nd$((NUM+1))
if modprobe lo; then
	ifc -i $LOOP -n 127.0.0.1/8 -s up -b 127.255.255.255
	route -a -i $LOOP -n 127.0.0.0/8
fi

) > /var/log/net.log 2>&1

if [ ! -e /etc/firstbootdate ]; then
	sh /sys/first_run.sh
fi

. /etc/rc/rand start
. /etc/rc/loop start

exec login
