#!/bin/sh

start()
{
	modprobe loop
}

stop()
{
	modprobe -r loop
}

up() 
{
	start
}

down()
{
	stop
}

status()
{
	modprobe -e loop
	return $?
}

if [ -z $1 ]; then
	echo "usage: $0 [start|stop|status|up|down]"
	return 1
fi

$1
