SCRIPT_NAME=elf
OUTPUT_FORMAT=elf64-x86-64
ELFSIZE=64
TEXT_START_ADDR=0x50000000
NO_REL_RELOCS=yes
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
COMMONPAGESIZE="CONSTANT (COMMONPAGESIZE)"
ARCH="i386:x86-64"
MACHINE=
NOP=0x90909090
TEMPLATE_NAME=elf32
GENERATE_SHLIB_SCRIPT=yes
LARGE_SECTIONS=yes
GENERATE_PIE_SCRIPT=yes
NO_SMALL_DATA=yes
SEPERATE_GOTPLT=22
OTHER_READONLY_SECTIONS='
PROVIDE (___rodata = DEFINED (.rodata) ? .rodata : 0);
. = ALIGN (16);
'
# Make _edata and .bss aligned by smuggling in an alignment directive.
OTHER_GOT_SECTIONS='. = ALIGN (16);'
